import type { Metadata } from "next";
import { Google_Sans} from "next/font/google";
import "@/styles/globals.css";
import React from "react";
import { cn } from "@/lib/utils";
import Telemetry from "@/components/telemetry";

const googleSans = Google_Sans({
    variable: "--font-google-sans",
    subsets: ["latin"]
});

export const metadata: Metadata = {
    title: "CS6460 Google Classroom Redesign",
    description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en"
            className={cn("h-full", "antialiased", googleSans.variable, "font-sans")}
        >
            <head>
                <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
                    rel="stylesheet" />
                <link href="https://fonts.googleapis.com/icon?family=Material+Icons+Outlined"
                    rel="stylesheet" />
                <link href="https://fonts.googleapis.com/icon?family=Material+Symbols+Outlined"
                    rel="stylesheet" />
            </head>
            <body className="min-h-full flex flex-col bg-[#f8fafd]">
                <Telemetry />
                {children}
            </body>
        </html>
    );
}
